version = 0.1

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "shiftbot-dev"
capabilities = "CAPABILITY_IAM"
image_repositories = [ ]

[default.global.parameters]
stack_name = "shiftbot-dev"
region = "us-west-2"

[default.sync.parameters]
template_file = "c:\\prog\\Python\\Python_Github\\shiftbot\\shiftbot_dev\\template.yaml"
dependency_layer = false
watch = true
